import './App.css';
import { BrowserRouter, Routes, Route} from "react-router-dom";
import { useState } from 'react';
import HomePage from './conponents/HomePage';
import Channel from './conponents/Channel';
import Bonus from './conponents/Bonus';


function App() {

//   const [wordsHebrew, setWordsHebrew] = useState(['מותק',
//   'לצלול',
//   'להנהיג',
//   'ובכן',
//  ' צורת היו עבר', 
//   'מישהו',
//   'לחכות',
//  ' גורם/כי',
//   'ליפול',
//  ' נפל(בעבר)',
//   'יודע',
//  ' צורת גוף עבר',
//  ' צורת הדגשה לעתיד ',
//   'אבל',
//  ' שלו, בבעלותו/בעלותי',
//   'מחזיק',
//   'שלי',
//   'לרקוד',
//   'חושך',
//  ' בין/בתוך',
//  ' נשק/זרועותי',
//   'יחף' ,
//   'דשא',
//   'הקשבה',
//   'שלנו' ,
//   'אומר',
//   'אמר',
//  ' ראה (בעבר)',
//  ' סיפר/ אמר',
//   'התקשר',
//  ' גדול/נהדר',
//  ' יותר טוב',
//  ' עלול /יתכן', 
//   'שלו',
//  ' שלה/לה/אותה',
//  ' היה (היה לו)',
//  ' אותו/לו',
//   'עושה',
//   'עשה',
//   'יש', 
//   'יש ב(he,she, it)',
//  ' יש/ישנו(משתמשים בשביל לתאר משהו קיים)', 
//  ' פועל עזר לציון זמן עתיד',
//  ' היה-עבר' ,
//  ' ציון היה יכול',
//   'מי',
//   'אותם',
//   'שלהם',
//  ' מעט/קטן',
//  ' כמות מסויימת',
//  ' משפט הכללה /הכל',
//  ' הרבה/חשוב',
//   'צריך',
//  ' על/על גביי',
//  ' לשבור/לפרוץ',
//  ' אפילו/גם/במידה שווה',
//  ' קיבל',
//  ' כגון/כזה',
//  ' איך',
//  ' לבוא/חהגיע',
//  ' יכול/פחית',
//  ' מעל',
//  ' גם',
//  ' ישן/מבוגר',
//   'מחשבה',
//  ' יָכֹל; אֶפְשָׁר, מֻתָּר; יִתָּכֵן, אוּלַי; הַלְוַאי, יְהִי רָצוֹן',
//  ' למרות זאת/בכל זאת' ,
//  ' ללא,בלי',
//   'אותנו',
//   'רחוק',
//  ' עשה להכין',
//  ' אדוני/מר',
//  ' פועל עזר לציון עתיד',
//  ' אי פעם/תמיד',
//  ' למרות זאת/בכל זאת',
//   'יד',
//  ' עניים',
//  ' שלו/שלה(במידה ויש ׳ אז זה קיצור של it is',
//  ' החמיץ/החטיא/מתגעגע',
//   'שיש',
//  ' שכל/דעה/תודעה',
//  ' שכל/בינה',
//  ' אחר/שונה/נוסף',
//  ' אלה/אותם/הללו',
//  ' להגיד לספר' ,
//  ' נראה/נדמה',
//  ' הניח/שם/הכניס',
//  ' לתת/לאפשר/להשכיר' ,
//  ' לוקח',
//  ' לקח בעבר',
//  ' עני/ירוד/מסכן',
//  ' מקום/אתר',
//  ' בוצע/עשוי',
//   'כאב',
//   'עצמו',
//   'עצמי' ,
//   'עצמה',
//   'מצאתי' ,
//   'מתחת',
//   'מספיק',
//   'בקרוב',
//   'לתת',
//   'אכן',
//   'שמאל' ,
//   'לקבל',
//  ' שמע/לשמוע',
//   'כיום',
//   'שילוב',
//   'כללי',
//  ' משמרת/כיוון/החלפה/תחבולה',
//   'גופני' ,
//   'חינוך' ,
//  ' להפחית' ,
//   'תחרות',
//  ' במקום זאת' ,
//   'מאמץ',
//  ' בתוך/במסרת',
//  ' שמח יותר' ,
//  ' יצא לאור',
//  ' לערב/לסבך/לגרור',
//   'מאות',
//  ' אחוז/%',
//   'מחקר',
//   'תרגיל',
//  ' שבועי/באופן שבועי',
//   'בחוץ',
//   'גישה' ,
//   'לגלות',
//   'ראשי',
//   'משתפר',
//   'הכנה',
//   'סביבה',
//  ' קיצור דרך',
//   'לעודד',
// '    אינטרקציות',
//  ' להתוודות /להודות' ,
//  ' יום יום' ,
//  ' הרגיש',
//   'להתחרות' ,
//  ' צמח/גדל/התפתח',
//  ' אני לא בכושר ',
//   'צורה' ,
//   'מערכת',
//   'מושפע',
//   'מנסה',
//   'אומץ',
//  ' כושר/כח סבל',
//   'הדדי',
//  ' אמון /נאמנות /ביטחון',
//   'עצמי' ,
//   'משמעת', 
//   'נפשי',
//   'כח',
//   'להביא',
//  ' לאחר מכן',
//   'רוב',
//   'ספק',
//  ' מול/נגד',
//   'עגול',
//  ' עד(עד ש/עד ל)',
//   'שניהם',
//   'הגעתי',
//   'להתלבש',
//  ' השתתף/לקח חלק',
//   'תמיכה' ,
//  ' לא הוגן',
//   'התנהגות',
//  ' פן(כמו פן חברתי)',
//  ' ראה (בעבר)',
//  ' התחיל(בעבר)',
//   'למי',
//  ' עִם זֹאת',
//  ' שאל (בעבר)',
//   'דבר',
//   'כמעט',
//   'רחוק',
//   'קפדני',
//   'ממליץ',
//   'אבד,נעלם',
//   'מעט' ,
//  ' לקרת/לעבר' ,  
//  ' צורת עבר של (give)',
//   'מילה',
//   'סובב',
//  ' סוגים/טוב לב',
//  ' בכה (בעבר)',
//   'חצי',
//   'הביא(עבר של המילה bring )',
//  ' להציב/להניח',
//  ' כל אחד',
//  ' לא צלחו',
//   'לתאר',
//   'חוויה',
//   'התרגשות',
//   'בעיקר',
//  ' להשיב/לענות',
//  ' משאלה/בקשה/איחול/ברכה',
//  ' כל משהו/שלם משהו/(קיץ שלם.חופשה שלמה.שבוע שלם)',
//   'תהליך',
//  ' אֹפֶן, צוּרָה; הִתְנַהֲגוּת; סִגְנוֹן',
//  ' הכי פחות/מעט',
//  ' עָנָה, הֵשִׁיב; פָּתַר; הֵגִיב',
//   'בין',
//  ' עמד/עצר/החזיק מעמד',
//  ' צורת עבר של stand',
//  ' יושב/שב',
//  ' ישב',
//  ' לעזוב/להשאיר משהו',
//  ' צורת עבר של (leave)',
//  ' פוטר',
//  ' לשמור',
//  ' שמר(keep בעבר )',
//   '????????????????',
//  ' פחות',
//  ' מתנה',
//  ' לעיתים קרובות ',
//  ' אשתי/רעיה',
//   'לשלוט',
//   'ליד',
//   'אישי',
//  ' עניין/חומר',
//   'הִנִּיחַ, שִׁעֵר, סָבַר /מקור (Just suppose for a moment that you agreed with me)',
//   'ניחש',
//  ' לוח שנה',
//   'נופים',
//   'מנוחה',
//  ' מיון/למיין',
//  ' חלף/עבר/העביר',
//  ' להניח/לשכיב',
//   'הניח/השכיב (צורת עבר של lay) ',
//   'מאחור',
//  ' טיפול/בזהירות',
//   'לבד',
//   'שיחה',
//  ' ארון בגדים',
//   'לפעמיים',
//  ' אחר(דבר אחר/מקום אחר)',
// '  פרק(פרק 3/פרק בחיים)',
//  ' כלכלה',
//  ' הפך ל/נעשה ל',
//   'אוויר',
//  ' אות/ מכתב',
//  ' סיבה/נימוק',
//  ' נאה/יפה',
//  ' מסויים(אדם מסויים) /בטוח(בטוח במשהו)',
//  ' צריך/חייב',
//   'מיטה',
//   'לקרוא',
//   'כבר',
//   'שיטות',
//   'תוצאות',
//  ' להתקבל(להתקבל לבית ספר)',
//   'תחרותי',
//   'להשיג',
//   'חיוניות',
//   'הגינות',
//  ' למרבה המזל',
//   'לצערי',
//   'חול',
//  ' כדור הארץ',
//   'נדרש',
//  ' מדבר / שממה',
//  ' יצר/הפיק',
//  ' איכות',
//  ' בנה/יסד/הקים',
//  ' חומר',
//   'גס',
//   'בנייה',
//  ' מטרה/כוונה',
//   'אגם',
//   'נהרות',
//  ' לגמרי/לחלוטין',
//   'חוסר',
//   'זמין',
//   'מקומי',
//   'מקורות',
//  ' במידה רבה',
//   'ניצול',
//  ' אספקה(הספקת מזון)',
//  ' אזל/נגמר',
//  ' כתוצאה מכך',
//  ' כפה/הכריח',
//   'לסמוך',
//   'מיובא',
//   'מסחר',
//   'במהירות',
//   'מתאים',
//  ' פעולות/מעשים',    
//   'נורא',
//   'משפט',
//   'צוחק' ,
//  ' פשוט(פשוט תקשיב/פשוט תעש את זה)',
//  ' הציצה/העיף מבט',
//  ' תנועה/תזוזה/פעילות',
//   'שריר',
//   'מצח',
//   'לחיים',
//   'שפתיים',
//  ' הבעות פנים',
//  ' ביטויי/הבעה',
//  ' גילה/חשף/הראה',
//   'רוחב',
//  ' מגוון רחב',
//  ' רגש/אמוציה',
//   'מצב',
//   'רמז',
//   'עמוק',
//  ' הזעיף את פניו',
//   'בקלות',
//  ' לספק/לתת(סיפק מידע/נתן מידע)',
//  ' פחד/אימה',
//  ' נֶהֱנָה, הִתְעַנֵּג',
//  ' הפתעה',
//  ' שעשוע' ,
//  ' הגדול ביותר',
//  ' אמונה',
//  ' כביש',
//  ' רישיון',
//  ' אמונה',
//  ' כביש',
//  ' רישיון',
//  ' להשקיע',
//  ' אני עושה טעות',
//  ' אני עשיתי טעות',
//  ' הייתי(עם פעולה) (הייתי הולך/הייתי עושה)',
//  ' הייתי (עם תיאור)',
//  ' חרטה/הצטערות',
//  ' יכול/מסוגל',
//  ' לחוד/בנפרד',
//  ' משקל',
//   'מפחיד',
//   'עצבני',
//  ' הבנתי(בעבר)',
// 'הנאה',
// 'או זה או זה',
// 'אמצעי' ,
// 'לדבר(בעבר)',
// 'לקיחה',
// 'דביבור שיח',
// 'ללכת',
// 'לכן/לפיכך',
// 'מעל/למעלה',
// 'שמח/מרוצה',
// 'ביקורת',
// 'טבע',
// 'עצמם',
// 'בקושי/כמעט ולא',,
// 'עיר',
// 'חוש/תחושה/רגש',
// 'פתגם',
// 'רצוי/מבוקש',
// 'לחזור/להחזיר',
// 'דוב',
// 'נראה/ הופיע' ,
// 'לאחרונה' ,
// 'הבטחה/מובטח/בערבות',
// 'לכן',
// 'בסדר גמור/טוב/הכל בסדר',
// 'מקרה',
// 'החזיק',
// 'בהחלט',
// 'קהילה',
// 'חברה',
// 'להמשיך',
// 'עמית/בחור',
// 'אמת' ,
// 'אפשרי',
// 'חושש/מפחד',
// 'כבוד',
// 'קרקע /אדמה',
// 'בלבד',
// 'בלתי רגיל/לא רגיל',
// 'רגיל',
// 'פתאום',
// 'גישה/יחס' ,
// 'לאחרונה' ,
// '  הבטחה/מובטח/בערבות',
//   'לכן',
//   'בהחלט',
//  ' עמית/בחור',
//  ' חושש/מפחד',
//  ' במידה רבה',
//   'מת',
//  ' מאחר/בסוף(מאחר לעבודה/ בסוף השנה)',
//   'לחיות',
//  ' אף אחד',
//   'מוות',
//   'מאמר',
//   'דור',
//  ' שעון/להסתכל',
//  ' יוצא דופן',
//  ' מפטפט/משוחח',
//   'בקצרה',
//   'טבעי',
//   'לדמיין',
//   'ציונים',
//  ' מחובר/חיבור',
//   'בתוך'
//   ]);
// const [wordsEnglish, setWordsEnglish] = useState([
//   'Darling',
//   'Dive',
//   'Lead',
//   'Well',
//   'Were',
//   'Someone',
//   'Wait', 
//   'Cause',
//   'To fall',
//   'Fell',
//   'Knowing' ,
//   'Was',
//   'Will',
//   'But',
//   'Own',
//   'Holding',
//   'Mine',
//   'Dance' ,
//   'Dark',
//   'Between',
//   'Arms',
//   'Barefoot',
//   'Grass',
//   'Listening',
//   'Our',
//   'To say',
//   'Said',
//   'Saw',
//   'Told',
//   'Called',
//   'Great',
//   'Better' ,
//   'Might' ,
//   'His',
//   'Her' ,
//   'Had',
//   'Him',
//   'Do',
//   'Did',
//   'Have',
//   'Has',
//   'There',
//   'Would',
//   'been',
//   'Could',
//   'Who',
//   'Them',
//   'Their',
//   'Little' ,
//   'Some',
//   'Any',
//   'Much' ,
//   'Should',
//   'Upon',
//   'Break' ,
//   'Even',
//   'Got',
//   'Such',
//   'How',
//   'Come',
//   'Can',
//   'Over',
//   'Too',
//   'Old',
//   'thought' ,
//   'May',
//   'Though',
//   'Without',
//   'Us',
//   'Away',
//   'make' ,
//   'Sir',
//   'Shall',
//   'Ever',
//   'Yet',
//   'Hand',
//   'Eyes',
//   'Its',
//   'Miss',
//   'Having',
//   'Mind',
//   'Intellect',
//   'another' ,
//   'those',
//   'tell',
//   'seem',
//   'Put',
//   'Let',
//   'Take',
//   'Took',
//   'Poor',
//   'Place',
//   'Done',
//   'Pain',
//   'himself' ,
//   'myself' ,
//   'herself' ,
//   'found',
//   'under',
//   'enough',
//   'soon',
//   'give',
//   'indeed',
//   'left',
//   'get',
//   'hear',
//   'currently',
//   'incorporating',
//   'general',
//   'shift',
//   'physical',
//   'education',
//   'reduce',
//   'competition',
//   'instead',
//   'effort',
//   'within' ,
//   'happier' ,
//   'published',
//   'involve',
//   'hundreds' ,
//    'Percent',
//   'Research',
//   'Exercise',
//   'Weekly' ,
//   'Outside',
//   'Approach',
//   'Discover',
//   'Main',
//   'Improving',
//   'Making',
//   'Environment',
//   'Shortcut',
//   'Encourage',
//   'Interactions',
//   'Admit',
//   'Daily',
//   'Felt',
//   'Competing',
//   'Grew',
//   'Im not in fit' ,
//   'Shape',
//   'System',
//   'Influence',
//   'Trying',
//   'Bravery',
//   'Stamina',
//   'Mutual',
//   'Trust',
//   'Self',
//   'Discipline',
//   'Mental',
//   'Strength',
//   'Bring',
//   'then' ,
//   'most',
//   'doubt',
//   'against' ,
//   'round',
//   'till',
//   'both' ,
//   'arrived',
//   'get dress',
//   'participate',
//   'support',
//   'Unfair' ,
//   'Behavior',
//   'Side',
//   'seen',
//   'began',
//   'whom'  ,
//   'however',
//   'asked',
//   'thing' ,
//   'almost',
//   'far',
//   'strict',
//   'recommend',
//   'gone' ,
//   'few',
//   'towards' ,
//   'gave' ,
//   'word' ,
//   'turned' ,
//   'kind'  ,
//   'cried'   ,
//    'Half',
//   'Brought',
//   'set' ,
//   'each' ,
//   'unsuccessful',
//   'describe',
//   'experience',
//   'excitement',
//   'mainly',
//   'reply',
//   'wish',
//   'whole',
//   'process',
//   'manner',
//   'least',
//   'answered',
//   'among',
//   'stand' ,
//   'stood',
//   'sit',
//   'sat',
//   'leave',
//   'left',
//   'laid off',
//   'keep',
//   'kept',
//      'taken', 
//   'Less',
//   'Present',
//   'often'     ,
//   'wife',
//   'master',
//   'next/near',
//   'personal',
//   'matters',
//   'suppose',
//   'guess',
//   'calendar',
//   'landscapes',
//   'rest',
//   'sort',
//   'pass/passing/passed',
//   'lay',
//   'laid',
//   'behind',
//   'care',
//   'alone',
//    'call',
//   'Wardrobe',
//   'Sometimes',
//   'Else',
//   'Chapter',
//   'Economy',
//   'Become',
//   'Air',
//   'Letter',
//   'Reason',
//   'pretty',
//   'certain',
//   'ought',
//   'bed',
//   'read',
//   'already',
//   'methods',
//   'results',
//   'be admitted' ,
//   'competitive',
//   'achieve',
//   'vitality',
//   'Decency',
//   'Fortunately',
//   'Unfortunately',
//   'sand' ,
//   'Earth',
//    'required',
//   'Deserts',
//   'Produce',
//   'Quality',
//   'Build',
//   'Materials',
//   'Coarse',
//   'Construction',
//   'Purposes',
//   'Lake',
//   'River',
//   'Completely',
//   'Lack',
//   'available',
//   'Local',
//   'Sources',
//   'Heavily',
//    'exploit',
//   'Supplies',
//   ' run out',
//   'Consequently',
//   'Force',
//   'Rely',
//   'Imported',
//   'Trade',
//   'Rapidly',
//    'suitable',
//   'Actions',
//   'Dire',
//   'Phrase',
//   'Laugh',
//   'Simply',
//   'Glance',
//   'Movement',
//   'Muscle',
//   'Forehead',
//   'Cheeks',
//    'lips',
//   'facial expressions',
//    'expression',
//   'reveal/discover',
//   'width',
//   'wide range' ,
//   'emotion',
//   'states',
//   'hint',
//   'deep',
//   'frown' ,
//   'easily',
//    'provide',
//   'Fear',
//   'Delight',
//   'Surprise',
//   'Amusement',
//   'Biggest',
//   'Faith',
//   'Road',
//   'License',
//   'Faith',
//   'Road',
//   'License',
//   'Invest',
//   'I make a mistake',
//   'I made a mistake',
//    'I would', 
//   'I was' ,
//   'Regret',
//   'Able',
//   'Separately',
//   'Weight',
//   'Scary',
//   'Nervous',
//   'Understood',
// 'pleasure',
// 'either/neither here nor there',
// 'means',
// 'spoke',
// 'taking',
// 'talk',
// 'walk',
// 'thus',
// 'above',
// 'glad',
// 'criticism',
// 'nature',
// 'themselves',
// 'hardly',
// 'town',
// 'sense',
// 'saying',
// 'wanted',
// 'return',
// 'bear',
// 'appear/בעבר עם ed ',
// 'recently',
// 'guaranteed , promis',
// 'therefore',
// 'fine'  ,         
// 'case',
// 'hold',
// 'certainly',
// 'society',
// 'company',
// 'continue',
// 'fellow',
// 'truth',
// 'possible',
// 'afraid',
// 'honour',
// 'ground',
// 'except',
// 'unusual', 
// 'usual' ,
// 'Suddenly',
// 'approach/attitude',
// 'recently',
//     'guarantee/promise',
//     'therefore',
//     'certainly',
//     'fellow',
//     'afraid',
//     'heavily',
//     'dead',
//     'late',
//     'live',
//     'none',
//     'death',
//     'article',
//     'generation',
//     'Watch',
//     'extraordinary',
//     'chatting',
//     'In short',
//     'natural',
//     'imagine',
//     'grades ',
//     'connection',
//     ' inside '
// ])



const [wordsHebrew, setWordsHebrew] = useState([
 ' בן אנוש',
  'אנושיות',
 ' קיבולת/תכולה/נפח',
 ' השתתף/לקח חלק',
 ' כמה(מגיע אחרי כמה של מספר מסויים)',
 ' בו זמנית',
 ' מי/אשר/ש...',
 ' לבשל ארוחת ערב',
 ' תקופה של 100 שנה',
 ' נוסע(מי שנימצא באוטו עם הנהג)',
 ' תופעה',
 ' להגיע/להשיג',
 ' באופן שיגרתי',
 ' התנהגות/ניהול',
  'להזמין',
 ' בית קולנוע',
 ' ניגוד/מנוגד',
  'דוגמא',
 ' מסויים(אדם מסויים)',
 ' במהלך(במהלך הנסיעה/במהלך החופשה)',
 ' תמיד יהיה']);
  const [wordsEnglish, setWordsEnglish] = useState([
   ' human being',
    'humanity',
     'capacity',
    'attend ',
    'several',
    ' simultaneously',
    'who',
    'cooked supper',
    'century',
    'passenger',
    'phenomenon',
    'reached',
    'routinely',
    'conduct',
    'order' ,
    'cinema',
    'contrast',
    'example',
    ' certain ',
    'during ',
    'will always be'])


const [addWordHebrew, setAddWordHebrew] = useState([])
const [addWordEnglish, setAddWordEnglish] = useState([])
const [show, setShow] = useState(true)
const [color, setColor] = useState('white')
const [title, setTitle] = useState('Reveal the answer')
const [num, setNum] = useState(23)
const [numAdd, setNumAdd] = useState(-1)
const [addWordH, setAddWordH] = useState([])
const [addWordE, setAddWordE] = useState([])

const rando = (setColor) => {
  setColor('white')
  setTitle('Reveal the answer')
  setShow(true)
  let ran = Math.floor(Math.random() * (num) + 1); // The maximum 
  console.log(ran);
  pushHebrew(ran)
  pushEnglish(ran)
  deletePost(ran)
  console.log(num);
  setNum(num - 1)
  console.log(num);
 

  return ran;
}

const toShow = (setColor) => {

  if (show === false) {
      setColor('white')
      setTitle('Reveal the answer')
      setShow(true)
      return
  }


  if (show === true) {
      setColor('black')
      setTitle('Hide the answer')
      setShow(false)
  }

}

  const pushHebrew = (ran) => {
    
    let as = wordsHebrew[ran]
    document.getElementById('h12').innerHTML = as;
    setAddWordHebrew(as)
}
  const pushEnglish = ( ran) => {
    
    let ad = wordsEnglish[ran]
    document.getElementById('h13').innerHTML = ad;
    setAddWordEnglish(ad)
}

const deletePost = (i) => {
  let newArr = wordsHebrew.filter((val, index) => (i != index))
  setWordsHebrew([...newArr])
  let newArrb = wordsEnglish.filter((val, index) => (i != index))
  setWordsEnglish([...newArrb])
}

const deletAdd = (i) => {
  let newArr = addWordH.filter((val, index) => (i != index))
  setAddWordH([...newArr])
  let newArrb = addWordE.filter((val, index) => (i != index))
  setAddWordE([...newArrb])

}
const addBonus = () => {
  let rand = Math.floor(Math.random() * (numAdd)); // The maximum 
  let he = addWordH[rand]
  document.getElementById('h89').innerHTML = he;
  let en = addWordE[rand]
  document.getElementById('h98').innerHTML = en;
  console.log(rand);
  deletAdd(rand)
  setNumAdd(numAdd - 1)
}
const addWordTo = () => {
  addWordH.push(addWordHebrew)
  setAddWordH(addWordH)
  addWordE.push(addWordEnglish)
  setAddWordE(addWordE)
  setNumAdd(numAdd + 1)
}

  return (
    <div className="App">
      
    <BrowserRouter>
    
        <div> <Channel  addWordTo={addWordTo}/> </div>
        <Routes>
          <Route path="/" element={<HomePage  rando={rando} toShow={toShow} color={color} title={title} wordsHebrew={wordsHebrew}  wordsEnglish={wordsEnglish}   addWordHebrew={addWordHebrew} addWordEnglish={addWordEnglish} addWordTo={addWordTo}/>} />
          <Route path="/bonus" element={<Bonus toShow={toShow} deletAdd={deletAdd} addBonus={addBonus} title={title} addWordTo={addWordTo} /> } />
        </Routes>
      </BrowserRouter>


    </div>
  );
}

export default App;
